# Generated by Django 4.2.4 on 2023-08-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discounted_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
