# Generated by Django 4.2.4 on 2023-08-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0006_brand_alter_product_description_product_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='for_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
    ]
