# Generated by Django 4.2.4 on 2023-08-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0009_alter_product_for_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
