# Generated by Django 4.2.4 on 2023-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0010_product_product_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
