# Generated by Django 4.2.4 on 2023-08-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0011_alter_product_product_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Packer',
            field=models.TextField(blank=True),
        ),
    ]
