# Generated by Django 4.2.4 on 2023-08-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0014_alter_product_for_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(null=True, upload_to='product_pics'),
        ),
    ]
