# Generated by Django 4.2.4 on 2023-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0016_product_featured_product_manufacturing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='entry_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
