# Generated by Django 4.2.4 on 2023-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0017_product_entry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='entry_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
