# Generated by Django 4.2.4 on 2023-08-31 15:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0020_rename_product_image_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addi_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
