# Generated by Django 4.2.4 on 2023-08-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0021_product_addi_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='addi_description',
            new_name='additional_description',
        ),
    ]
