# Generated by Django 4.2.4 on 2023-09-10 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothesapp', '0023_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipping_charges', models.IntegerField()),
                ('grand_total', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('paytm', 'Paytm'), ('gpay', 'Google pay')], max_length=16)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.IntegerField()),
                ('zip', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('order_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothesapp.order')),
            ],
        ),
    ]
