# Generated by Django 4.2.4 on 2023-09-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0024_order_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('shipped', 'Order Shipped'), ('received', 'Order Received'), ('processing', 'Order Processing'), ('delivered', 'Order Delivered'), ('complete', 'Order Complete')], default='received', max_length=15, null=True),
        ),
    ]
