# Generated by Django 4.2.4 on 2023-09-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0027_alter_order_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothesapp.product'),
        ),
    ]
