# Generated by Django 4.2.4 on 2023-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0029_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopByCatgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_category', models.CharField(max_length=100)),
            ],
        ),
    ]
