# Generated by Django 4.2.4 on 2023-09-28 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothesapp', '0030_shopbycatgory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clothesapp.shopbycatgory'),
        ),
    ]
